packages:
  - blueman
  - containerd.io
  - curl
  - docker-buildx-plugin
  - docker-ce
  - docker-ce-cli
  - docker-compose-plugin
  - firefox
  - gcc
  - git
  - i3lock
  - jq
  - libglvnd-gles
  - make
  - nordvpn
  - thunderbird
  - tmux
  - unzip
  - wget
  - xclip
  - xfce4-power-manager

directories:
  - ~/.local
  - ~/.local/bin
  - ~/.local/cache
  - ~/code
