packages:
  - blueman
  - containerd.io 
  - curl
  - docker-buildx-plugin 
  - docker-ce 
  - docker-ce-cli 
  - docker-compose-plugin
  - firefox
  - gcc
  - git
  - i3lock
  - lpf-spotify-client
  - jq
  - make
  - nordvpn
  - thunderbird
  - tmux
  - unzip
  - wget
  - xclip

directories:
  - ~/.local
  - ~/.local/bin
  - ~/.local/cache
  - ~/code
  
